services:
  - type: web
    name: valentines
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
```

**OR** if you don't want to use `render.yaml`:

Add a `_redirects` file in your `public` folder:
```
/*    /index.html   200